### ISSUE TITLE
[SUGGESTION] Could you add ScrapydWeb to the list

### ISSUE THREAD

**Issue by my8100** [michael-yin/awesome-scrapy#1]
[ScrapydWeb](https://github.com/my8100/scrapydweb) is a full-featured web UI for Scrapyd cluster management, with Scrapy log analysis & visualization supported. Other features include Basic auth, Auto packaging, Timer Tasks, Email notice, and Mobile UI.

**Comment by michael-yin** [comment]
@my8100 

I already added it to the list.

Thx.
